#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $STONEDLEGEND_REPO == "STONED-LEGEND-ASSISTANT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $STONEDLEGEND_REPO == "STONED-LEGEND-ASSISTANT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $STONEDLEGEND_REPO =~ $regex ]]
    then
        if [[ $STONEDLEGEND_REPO_BRANCH ]]
        then
            echo "${STONEDLEGEND_REPO}/archive/${STONEDLEGEND_REPO_BRANCH}.zip"
        else
            echo "${STONEDLEGEND_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="STONEDLEGENDASSISTANT.zip"
    echo "  ⚜Downloading STONED LEGEND ASSISTANT.1Source Code...❤"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    STONEDLEGENDPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  LegendBot V2.1 Cleaning.."
    rm -rf "$zippath"
    sleep 5
    cd $STONEDLEGENDPATH
    echo "    • Starting 𝙎𝙏㋛︎𝙉𝚵𝘿✫𝐿𝚵Ⴚ𝚵𝙉𝘿✫  •    "
    echo "
    LEGENDBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
